spring:
  application:
    name: spring-cloud-netflix-service-admin
  zipkin:
    base-url: http://localhost:8084
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/