spring:
  application:
    name: spring-cloud-netflix-admin
  zipkin:
    base-url: http://localhost:8084

server:
  port: 8085

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/