spring:
  application:
    name: spring-cloud-netfilx-eureka
  zipkin:
    base-url: http://localhost:8084
server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/