spring:
  application:
    name: spring-cloud-netflix-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/