spring:
  application:
    name: spring-cloud-netflix-admin-client
  boot:
    admin:
      client:
        url: http://localhost:8085
  zipkin:
    base-url: http://localhost:8084

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/